= Trinity: Frequently Asked Questions =

link:index.html[Trinity-home]

- <<ques_why_so_many_transcripts, There are too many transcripts! What do I do?>>
- <<ques_comp_resources_required, What computing resources are required?>>
- <<ques_how_long, How long should this take?>>
- <<ques_computing_grid, How can I run this in parallel on a computing grid?>>
- <<ques_reads_in_assembly, How do I identify the specific reads that were incorporated into the transcript assemblies?>>
- <<ques_mult_seq_libraries, How do I combine multiple libraries in a single Trinity run? Or how do I combine paired and single reads?>>
- <<ques_bad_alloc, Trinity process died due to 'std::bad_alloc' >>
- <<ques_butterfly_GC_thread_fail, Butterfly fails with java Error: Cannot create GC thread. Out of system resources.>> 
- <<ques_change_kmer_size, How do I change the K-mer size?>>
- <<ques_combine_SS_w_DS_reads, Can I combine strand-specific and non-strand-specific reads?>>


[[ques_why_so_many_transcripts]]
== There are too many transcripts!  What do I do? ==

Welcome to RNA-Seq de novo assembly!  :)  There are several aspects of de novo assembled transcripts to be aware of:

-  *Lots* of transcripts is the rule rather than the exception.  

-  Most of the transcripts are very lowly expressed, and the deeper you sequence and the more complex your genome, the larger the number of lowly expressed transcripts you will be able to assemble.  Biological relevance of the lowly expressed transcripts could be questionable - some are bound to be very relevant.

-  There's really no good reason to filter them out.  They can be 'passengers' throughout all of your data analyses, and if any of them are important, they'll ideally surface in the relevant study.   You can put them all through Trinotate.github.io for annotation/analysis, and you can put them through DE studies just fine (those with insufficent reads will get naturally filtered out during DE studies).  If the read counts are few or lacking, they simply won't surface as significant DE entries, but if there's protein homology or other interesting features, you'll continue to capture this info.

-  If you want to guestimate 'how many expressed genes/transcripts do I really have?', then examine link:abundance_estimation.html#how_many_expr[counts of transcripts or genes vs. min expression thresholds]. This will enable you to count the number that reflect the majority of the reads, excluding counting those that have little read support.  The entries with >= ~1 fpkm or tpm tend to be heavily enriched for transcripts that correspond to what we typically think of as 'genes' in the pre-RNA-Seq era, and what typically are awarded annotation status in genome annotation. 

-  If for some reason you do want to filter out those transcripts that have little read support, you can link:abundance_estimation.html#filtering_transcripts[filter them based on the RSEM abundance estimates].

-  If you're concerned about having too many isoforms for a given gene, you can use the filtering method above to remove isoforms that are weakly expressed compared to more dominant isoforms.  Also, you can simply perform DE analysis at the 'gene' level in addition to the 'isoform' level, so as to increase your power for DE analysis.  Other methods such as http://genomebiology.com/2014/15/7/410[Corset] can also be used to regroup relevant transcripts into 'gene' clusters.


[[ques_comp_resources_required]]
== What computing resources are required? ==

Ideally, you will have access to a large-memory server, roughly having ~1G of RAM per 1M reads to be assembled.  The memory usage mostly depends on the complexity of the RNA-Seq data set, specifically on the number of unique k-mers.  If you do not have access to a high-memory server, link:index.html#RunElsewhere[other freely available options are available].

[[ques_how_long]]
== How long should this take? ==

Trinity run-time depends on a number of factors including the number of reads to be assembled and the complexity of the transcript graphs.  The assembly from start to finish can take anywhere from ~1/2 hour to 1 hour per million reads (your mileage may vary).


[[ques_computing_grid]]
== How can I run this in parallel on a computing grid? ==

The initial Inchworm and Chrysalis steps currently need to be run on a single server, however parts of Chrysalis and all of Butterfly can be run as naive parallel processes on a computing grid. Both SGE and LSF are currently supported. Configuring Trinity for leveraging these grid-computing platforms is described link:index.html#Computing_Grid[here].


[[ques_reads_in_assembly]]
== How do I identify the specific reads that were incorporated into the transcript assemblies? ==

Currently, the mappings of reads to transcripts are not reported.  To obtain this information, we recommend realigning the reads to the assembled transcripts using http://bowtie-bio.sourceforge.net/index.shtml[Bowtie]. Capturing both properly paired read alignments and single unpaired alignments can be captured and quantified as described link:analysis/abundance_estimation.html#detailed_assessment[here].


[[ques_mult_seq_libraries]]
== How do I combine multiple libraries in a single Trinity run? Or, how do I combine paired and single reads? ==

If you have RNA-Seq data from multiple libraries and you want to run them all through Trinity in a single pass, simply combine all your left.fq files into one left.fq file, and combine all right.fq files into one right.fq file. Then run Trinity using these separately concatenated left and right input files.  

If you have additional singletons, add them to the .fq file that they correspond to based on the sequencing method used (if they're equivalent to the left.fq entries, add them there, etc).

There is no good way to combine strand-specific data with non-strand-specific data, unless you decide to treat the entire data set as non-strand-specific.


[[ques_bad_alloc]]
== Trinity process died due to 'std::bad_alloc' ==

This is an indicator that the process ran out of available RAM. If you have more RAM resources to make available to Trinity, then simply rerun your original Trinity command with the altered resources allocated and it should resume approximately where it left off.  

If you are resource limited, please consider running Trinity link:index.html#RunElsewhere[here].  If you want to continue to try to run Trinity given your available resources, you can reduce the total RAM requirements by running Trinity with parameter '--min_kmer_cov 2'. Although the assembly should still be of high quality and require less RAM, lowly expressed transcripts may be more highly fragmented in the assembly.


[[ques_butterfly_GC_thread_fail]]
== Butterfly fails with java Error: Cannot create GC thread. Out of system resources. ==

There are a couple reasons why this error message might creep up.

1.  *all memory has been consumed on the machine*.  Each butterfly process wants to reserve 10G of maximum heap space.  If there's less than 10G of free memory on the machine per butterfly (--CPU setting), then java may not be able to initialize (depends on your OS configuration).  Try reducing the --CPU setting and rerunning your Trinity command. It should resume where it left off.

2.  *NUMA architecture*:  one of our users found that the java invocation required: -XX:ParallelGCThreads=<Numerical Thread Count>, otherwise it would try to use too many threads.

[[ques_change_kmer_size]]
== How do I change the K-mer size ==

Although Inchworm has the capability of running independently with different k-mer sizes up to 32 (the 64-bit limit with 2-bit base encoding), Chrysalis and Butterfly are current fixed at the 25mer k-mer size.  In testing, we discovered early on that 25-mers appeared to be near-optimal across a different transcriptomes and different read abundance levels, and so fixed the value accordingly as part of the Trinity process.  Future development will aim to expose the k-mer setting as an option.

[[ques_combine_SS_w_DS_reads]]
== Can I combine strand-specific and non-strand-specific reads? ==

You can do so, but you wouldn't be able to benefit as from the strand-specificity, since you'll need to run Trinity in non-strand-specific mode.


